#ifndef SYSTEM_EVENTS_H
#define SYSTEM_EVENTS_H

#include "esp_event.h"
#include "system_err.h"

ESP_EVENT_DECLARE_BASE(APP_EVENTS);
ESP_EVENT_DECLARE_BASE(CORE_EVENTS);

typedef enum {
  APP_EVENT_NETWORK_UP = 400,
  APP_EVENT_NETWORK_DOWN = 401,
  APP_EVENT_MQTT_CONNECTED = 402, 
  APP_EVENT_MQTT_DISCONNECTED = 403,
  APP_EVENT_MODBUS_NETWORK_UP = 404,
  APP_EVENT_MODBUS_NETWORK_DOWN = 405,
  APP_EVENT_SYSTEM_FAULT = 406
} app_event_id_t;

typedef enum {
  CORE_EVENT_FAULT_LOW_PRESSURE = 700,
  CORE_EVENT_FAULT_LOW_SALT = 701,
  CORE_EVENT_REGEN_STARTED = 702,
  CORE_EVENT_REGEN_COMPLETED = 703,
  CORE_EVENT_FAULT_DATA_LOSS = 704,
  CORE_EVENT_REGEN_FAILED = 705
} core_event_id_t;

#endif